package plugins.org.craftercms.aiassistant.prompt

/**
 * Keys accepted for site overrides {@code /scripts/aiassistant/prompts/&lt;KEY&gt;.md}
 * (must match {@link ToolPrompts} {@code p('KEY', ...)} usages).
 * <p>Prefixes: {@code GENERAL_} (cross-cutting Studio / LLM policy), {@code CMS_CONTENT_} (repository content,
 * translate, preview, publish), {@code CMS_DEVELOPMENT_} (templates, content types, analyze).</p>
 * <p>When adding a new {@code p('NEW_KEY', ...)} in {@link ToolPrompts}, append here.</p>
 */
final class ToolPromptsOverrideCatalog {

  private ToolPromptsOverrideCatalog() {}

  static final List<String> KEYS = [
    'CMS_CONTENT_DESC_GENERATE_IMAGE',
    'CMS_CONTENT_DESC_GET_CONTENT',
    'CMS_CONTENT_DESC_GET_CONTENT_VERSION_HISTORY',
    'CMS_CONTENT_DESC_GET_PREVIEW_HTML',
    'CMS_CONTENT_DESC_LIST_CONTENT_TRANSLATION_SCOPE',
    'CMS_CONTENT_DESC_LIST_PAGES_AND_COMPONENTS',
    'CMS_CONTENT_DESC_PUBLISH_CONTENT',
    'CMS_CONTENT_DESC_REVERT_CHANGE',
    'CMS_CONTENT_DESC_TRANSFORM_CONTENT_SUBGRAPH',
    'CMS_CONTENT_DESC_TRANSLATE_CONTENT_BATCH',
    'CMS_CONTENT_DESC_TRANSLATE_CONTENT_ITEM',
    'CMS_CONTENT_DESC_UPDATE_CONTENT',
    'CMS_CONTENT_DESC_WRITE_CONTENT',
    'CMS_CONTENT_TRANSFORM_SUBGRAPH_SYSTEM',
    'CMS_CONTENT_TRANSLATE_ITEM_INNER_SYSTEM',
    'CMS_CONTENT_TRANSLATE_ITEM_INNER_SYSTEM_RAW',
    'CMS_CONTENT_TRANSLATE_ITEM_INNER_USER_APPENDIX',
    'CMS_CONTENT_TRANSLATE_ITEM_INNER_USER_APPENDIX_RAW',
    'CMS_CONTENT_UPDATE_CONTENT',
    'CMS_CONTENT_UPDATE_CONTENT_FORM_ENGINE',
    'CMS_DEVELOPMENT_ANALYZE_TEMPLATE',
    'CMS_DEVELOPMENT_DESC_ANALYZE_TEMPLATE',
    'CMS_DEVELOPMENT_DESC_GET_CONTENT_TYPE_FORM_DEFINITION',
    'CMS_DEVELOPMENT_DESC_GET_CRAFTERIZING_PLAYBOOK',
    'CMS_DEVELOPMENT_DESC_LIST_STUDIO_CONTENT_TYPES',
    'CMS_DEVELOPMENT_DESC_UPDATE_CONTENT_TYPE',
    'CMS_DEVELOPMENT_DESC_UPDATE_TEMPLATE',
    'CMS_DEVELOPMENT_UPDATE_CONTENT_TYPE',
    'CMS_DEVELOPMENT_UPDATE_CONTENT_TYPE_FORM_ENGINE',
    'CMS_DEVELOPMENT_UPDATE_TEMPLATE',
    'CMS_DEVELOPMENT_UPDATE_TEMPLATE_FORM_ENGINE',
    'GENERAL_DESC_FETCH_HTTP_URL',
    'GENERAL_DESC_GENERATE_TEXT_NO_TOOLS',
    'GENERAL_DESC_QUERY_EXPERT_GUIDANCE',
    'GENERAL_LLM_AUTHORING_INSTRUCTIONS',
    'GENERAL_LLM_AUTHORING_INTENT_EXPANSION_SYSTEM',
    'GENERAL_LLM_CHAT_ONLY_SYSTEM',
    'GENERAL_LLM_FORM_ENGINE_SUPPRESS_REPO_WRITES',
    'GENERAL_LLM_PLAN_GATE_ASSISTANT_ACK',
    'GENERAL_LLM_PLAN_GATE_USER_RETRY',
    'GENERAL_LLM_PLAN_ONLY_PHASE_SYSTEM',
    'GENERAL_LLM_POST_EXECUTION_REVIEW_SYSTEM',
    'GENERAL_LLM_USER_MESSAGE_TOOLS_POLICY_PREFIX',
    'GENERAL_XML_REPAIR_REMINDER_AFTER_BAD_READ'
  ].asImmutable()
}
